# Generated by Django 6.0.2 on 2026-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_size_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
